services:
  lab9:
    image: php:8.2-cli
    container_name: lab9_app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - "8001:8000"   # доступ с локального 8001
    command: >
      sh -c "
      if [ ! -f /usr/local/bin/composer ]; then
        php -r \"copy('https://getcomposer.org/installer', 'composer-setup.php');\" &&
        php composer-setup.php --install-dir=/usr/local/bin --filename=composer &&
        php -r \"unlink('composer-setup.php');\";
      fi &&
      composer install &&
      php artisan key:generate &&
      php artisan serve --host=0.0.0.0 --port=8000
      "
